# Remove the version line (optional, it's deprecated)

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node backend service
  api:
    build: .       # current folder (server/database)
    container_name: api_container
    ports:
      - "3030:3030"
    depends_on: 
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/dealershipsDB

volumes:
  mongo_data: {}
